global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    # Supposed to scrape the frontend, won't work because Vite doesn't run a node server
    - job_name: "app_monitor"
      scrape_interval: 5s
      static_configs:
          - targets:
                - "172.30.0.3:5173"

    # Monitoring go with prometheus
    - job_name: "api_monitor"
      scrape_interval: 5s
      static_configs:
          - targets:
                - "172.30.0.2:8080"
